#version 450

/// Fullscreen Quad Fragment Shader
///
/// This shader demonstrates:
/// - Texture sampling from compute shader output
/// - Simple texture lookup without additional processing
/// - set=0, binding=0 descriptor for fractal texture

/// Fragment shader inputs
layout(location = 0) in vec2 fragTexCoord;

/// Fragment shader outputs
layout(location = 0) out vec4 outColor;

/// Fractal texture (sampler2D, not storage image)
/// The compute shader writes to a storage image, but we sample it as a regular texture
/// set=0, binding=0 matches our descriptor set layout
layout(set = 0, binding = 0) uniform sampler2D fractalTexture;

void main() {
	/// Simple texture lookup - the fractal was generated by the compute shader
	/// and transitioned to SHADER_READ_ONLY_OPTIMAL layout for optimal sampling
	outColor = texture(fractalTexture, fragTexCoord);
}
