#pragma once

#include "mesh.h"
#include <glm/glm.hpp>

namespace lillugsi::rendering {

/// Torus mesh generated by revolving a circle around an axis
/// Creates a doubly-curved surface excellent for testing PBR materials and normal mapping
class TorusMesh : public Mesh {
public:
	/// Construct a torus with specified dimensions and tessellation
	/// @param majorRadius Distance from torus center to tube center (ring radius)
	/// @param minorRadius Radius of the tube cross-section
	/// @param majorSegments Number of segments around the major circle
	/// @param minorSegments Number of segments around the tube
	explicit TorusMesh(
		float majorRadius = 1.0f,
		float minorRadius = 0.3f,
		uint32_t majorSegments = 48,
		uint32_t minorSegments = 24
	);

	void generateGeometry() override;

	/// Get the major radius (distance from center to tube center)
	[[nodiscard]] float getMajorRadius() const { return this->majorRadius; }

	/// Get the minor radius (tube radius)
	[[nodiscard]] float getMinorRadius() const { return this->minorRadius; }

	/// Get the number of segments around the major circle
	[[nodiscard]] uint32_t getMajorSegments() const { return this->majorSegments; }

	/// Get the number of segments around the tube
	[[nodiscard]] uint32_t getMinorSegments() const { return this->minorSegments; }

private:
	float majorRadius;
	float minorRadius;
	uint32_t majorSegments;
	uint32_t minorSegments;

	/// Compute vertex position using parametric torus equations
	/// @param u Angle around major circle [0, 2π]
	/// @param v Angle around tube [0, 2π]
	[[nodiscard]] glm::vec3 computePosition(float u, float v) const;

	/// Compute analytical normal vector
	/// @param u Angle around major circle [0, 2π]
	/// @param v Angle around tube [0, 2π]
	[[nodiscard]] glm::vec3 computeNormal(float u, float v) const;
};

} /// namespace lillugsi::rendering
